apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcgan
  namespace: dl
  labels:
    app: dcgan        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcgan
  template:
    metadata:
      labels:
        app: dcgan
    spec:
      containers:
      - name: pytorch-cifar10-dcgan-64-0002-25
        image: dcgan:1.0.1
        imagePullPolicy: IfNotPresent
          # args:
          # - --batchSize
          # - "128"
          # - --niter
          # - "15"
          # - --lr
          # - "0.0002"

