global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
    - targets: ["0.0.0.0:9100"]
    metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: '(node_cpu_seconds_total|node_memory_MemAvailable_bytes|node_memory_MemTotal_bytes)'
      action: keep

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['0.0.0.0:8080']
    metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: '(container_cpu_usage_seconds_total)'
      action: keep
