{
 "title": "Kubernetes",
 "tags": [
  "cadvisor",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,kubernetes_io_hostname)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", instance=~\"$host\"},label_app)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", kubernetes_io_hostname=~\"$host\", pod=~\"$app.*\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", container!~\"^(POD|)$\"}[1m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", container!~\"^(POD|)$\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pod Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Container I/O",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Pods/Containers Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod))",
     "legendFormat": "Pods"
    },
    {
     "expr": "count(sum(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", image!=\"registry.k8s.io/pause:3.9\"}) by (pod, container))",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$app.*\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$app.*\", phase=~\"Failed\"}) by (phase, pod, namespace) > 0",
     "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$app.*\", phase=~\"Pending\"}) by (phase, pod, namespace) > 0",
     "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$app.*\", phase=~\"Unknown\"}) by (phase, pod, namespace) > 0",
     "legendFormat": "{{phase}}:{{namespace}}:{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$app.*\", phase=~\"Running|Succeeded\"}) == sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$app.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod:Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", container!~\"^(POD|)$\", image!=\"registry.k8s.io/pause:3.9\"}[1m])) by (pod, container)",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Pod:Container Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", container!~\"POD|\"}) by (pod, container)",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU Limits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{node=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", container=~\"$container\", resource=\"cpu\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$app(.*)\", container=~\"$container\", resource=\"memory\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m])) by (pod)",
     "legendFormat": "Transmit: {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m])) by (pod)",
     "legendFormat": "Receive: {{pod}}"
    }
   ]
  },
  {
   "title": "Pod:Container I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    container=~\"$container\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m])) by (pod, container)",
     "legendFormat": "Reads: {{pod}}:{{container}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    container=~\"$container\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m])) by (pod, container)",
     "legendFormat": "Writes: {{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Pod Network Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Pod:Container I/O",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    container=~\"$container\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{\n    kubernetes_io_hostname=~\"$host\",\n    namespace=~\"$namespace\",\n    pod=~\"$app.*\",\n    container=~\"$container\",\n    container!~\"POD\",\n    name=~\".+\"\n  }[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Workload Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{kubernetes_io_hostname=~\"$host\", namespace=~\"$namespace\", pod=~\"$app.*\", pod=~\".+\", container=~\"$container\", container!~\"POD|\", image!=\"registry.k8s.io/pause:3.9\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$app(.*)\", container=~\"$container\", resource=\"cpu\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$app(.*)\", container=~\"$container\", resource=\"memory\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}