{
 "title": "OS",
 "description": "Used Jobs:\n- \"node-exporter\"\n- \"process-exporter\"\n- \"service-exporter\"\n- \"proxmox-exporter\"",
 "tags": [
  "node-exporter",
  "proxmox",
  "data",
  "compute",
  "earth"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "vm",
    "label": "VM",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{instance=~\"$vm\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - ((node_memory_MemAvailable_bytes{instance=~\"$vm\"}) / (node_memory_MemTotal_bytes{instance=~\"$vm\"}))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((node_memory_SwapTotal_bytes{instance=~\"$vm\"} - node_memory_SwapFree_bytes{instance=~\"$vm\"}) / (node_memory_SwapTotal_bytes{instance=~\"$vm\"})) * 100 > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$vm\"}[$__rate_interval]) * 8)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$vm\"}[$__rate_interval]) * 8)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Load Average 1 minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$vm\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$vm\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$vm\"} - node_memory_MemAvailable_bytes{instance=~\"$vm\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$vm\", mode=\"idle\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$vm\"} - node_boot_time_seconds{instance=~\"$vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{instance=~\"$vm\", mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "System Load Average 1 minute by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores by Instance",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$vm\", mode=\"idle\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((node_memory_MemAvailable_bytes{instance=~\"$vm\"}) \n     / (node_memory_MemTotal_bytes{instance=~\"$vm\"}))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$vm\"} - node_memory_MemAvailable_bytes{instance=~\"$vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory by Instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$vm\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Memory by Instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"$vm\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Utilization by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$vm\"} - node_memory_SwapFree_bytes{instance=~\"$vm\"}) / (node_memory_SwapTotal_bytes{instance=~\"$vm\"})) * 100 > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Used by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$vm\"} - node_memory_SwapFree_bytes{instance=~\"$vm\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total SWAP by Instance",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$vm\"}) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "172.16.104.X Bytes by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$vm\", device=\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$vm\", device=\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Other Interfaces Bytes by Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$vm\", device!~\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$vm\", device!~\"ens18\"}[$__rate_interval]) * 8) by (instance)",
     "legendFormat": "{{instance}} - Transmit"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$vm\"}[$__rate_interval]) * 8) ",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$vm\"}[$__rate_interval]) * 8)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "OS Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$vm\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=~\"$vm\", mountpoint=\"/\"}) / node_filesystem_size_bytes{instance=~\"$vm\", mountpoint=\"/\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$vm\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=~\"$vm\", mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Disk Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$vm\", mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Disk Free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$vm\", mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"$vm\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interrupts by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_intr_total{instance=~\"$vm\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk IOps Completed by Instance",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_reads_completed_total{instance=~\"$vm\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Reads completed"
      },
      {
       "expr": "avg(irate(node_disk_writes_completed_total{instance=~\"$vm\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk IOps Completed by Device",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_reads_completed_total{instance=~\"$vm\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "avg(irate(node_disk_writes_completed_total{instance=~\"$vm\"}[$__rate_interval])) by (device)",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Processes in runnable state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_procs_running{instance=~\"$vm\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Processes blocked waiting for I/O to complete",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_procs_blocked{instance=~\"$vm\"} > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}