apiVersion: apps/v1
kind: Deployment
metadata:
  name: convnet
  namespace: dl
  labels:
    app: convnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convnet
  template:
    metadata:
      labels:
        app: convnet
    spec:
      containers:
      - name: convnet
        image: convnet:1.0.0
        imagePullPolicy: IfNotPresent

