apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
    role: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'cadvisor'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: k8s-cadvisor-tuned
      - source_labels: [__meta_kubernetes_pod_label_role]
        action: keep
        regex: monitoring

    - job_name: 'kube-state-metrics'
      scheme: http
      static_configs:
      - targets:
        - kube-state-metrics-tuned.monitoring.svc.cluster.local:10101

    - job_name: 'node-exporter'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: node-exporter
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: node-exporter-tuned

