apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus
    role: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090          # The port the service exposes
      targetPort: 9090    # The container port to forward to
      nodePort: 30090     # The external port on the node
