apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics-tuned
    app.kubernetes.io/version: 2.13.0
    app: kube-state-metrics-tuned
    role: monitoring
  name: kube-state-metrics-tuned
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics-tuned
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kube-state-metrics-tuned
        app.kubernetes.io/version: 2.13.0
        app: kube-state-metrics-tuned
    spec:
      automountServiceAccountToken: true
      containers:
      - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0
        args:
          - --metric-labels-allowlist=pods=[*]
        livenessProbe:
          httpGet:
            path: /livez
            port: http-metrics
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
        readinessProbe:
          httpGet:
            path: /readyz
            port: telemetry
          initialDelaySeconds: 5
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
      - image: sleepmaps/scripts:k8s-kube-state-metrics-tuned-1.0.8
        name: kube-state-metrics-tuned
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10101
          hostPort: 10101
          name: tuned-metrics
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
      serviceAccountName: kube-state-metrics
