apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cadvisor-tuned
subjects:
  - kind: ServiceAccount
    name: k8s-cadvisor-tuned  # Replace with the correct service account name if different
    namespace: monitoring  # Replace with the correct namespace
roleRef:
  kind: ClusterRole
  name: k8s-cadvisor-tuned
  apiGroup: rbac.authorization.k8s.io

