apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    role: monitoring
spec:
  selector:
    app: prometheus
    role: monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      name: http

