apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-fetcher
  namespace: sac
  labels:
    app: metric-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-fetcher
  template:
    metadata:
      labels:
        app: metric-fetcher
    spec:
      restartPolicy: Always
      containers:
        - name: metric-fetcher
          image: metric-fetcher:1.0.5
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4223
            name: http
            protocol: TCP
