apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  labels:
    app: grafana
    role: monitoring
spec:
  selector:
    app: grafana
    role: monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http-grafana

