{
 "title": "SAC",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Job Training Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "avg(job_training_progress)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Job Training Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "avg(job_training_accuracy)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Job Training Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "avg(job_training_loss)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "count(job_training_loss)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Node Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(node_mem_utilization) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(node_cpu_utilization) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(node_gpu_utilization) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}